######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 4 23:05:43 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . inc src
INCLUDEPATH += .

# Input
HEADERS += inc/layout.h inc/player.h
SOURCES += src/layout.cpp src/main.cpp src/player.cpp
