HEADER= global.h \
	    Contact.h\
		ContactManager.h
SOURCE = server.cpp\
        ContactManager.cpp
    
		
		
output:$(HEADER)
	g++ -g  $(SOURCE)
clean:
	rm	*.*.gch  .*.*.swp *~ *.o

distclean:
	rm a.out
