@startuml

package "Peer1Widget" {
    !rectangle "PeerWidget" {
        !QUdpSocket
        !QTextEdit
        !QTextEdit
        !QPushButton
    }
}

package "Peer2Widget" {
    !rectangle "PeerWidget" {
        !QUdpSocket
        !QTextEdit
        !QTextEdit
        !QPushButton
    }
}

Peer1Widget -- Peer2Widget: QUdpSocket bind(12345) / QUdpSocket bind(12346)

Peer1Widget -> Peer2Widget: writeDatagram
Peer2Widget -> Peer1Widget: writeDatagram

Peer1Widget -> Peer1Widget: readyRead() -> readPendingDatagrams()
Peer2Widget -> Peer2Widget: readyRead() -> readPendingDatagrams()

@enduml
